# Generated by Django 5.0.2 on 2024-03-08 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=254729583152, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be from Kenya', regex='^\\+?254\\d{9}$')]),
            preserve_default=False,
        ),
    ]
