# Generated by Django 5.0.2 on 2024-03-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
