# Generated by Django 5.0.2 on 2024-03-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0003_remove_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
